# Multi-tenancy
auth_enabled: false

# Loki's web server
server:
  http_listen_port: 3100 # def
  log_level: warn

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki

  storage:
    filesystem:
      chunks_directory: /loki/chunks

  replication_factor: 1 # Copies of each chunk across instances

  ring: # tracking which instance  responsible for which logs. Needs a key-value store
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24 # use this schema for all logs from this date onward
      store: tsdb # TSDB = Time Series Database — optimized for time-based log lookups
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  wal:
    enabled: true
    dir: /loki/wal
    flush_on_shutdown: true # flush all WAL data to chunks before exiting - clean restarts

  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s

  chunk_encoding: snappy # Compression algorithm used for chunks
  chunk_idle_period: 30m # If a stream  hasn't sent logs, close the chunk and flush it to disk even if not full.

  max_chunk_age: 2h # Force-flush chunk even when receiving logs. Prevents from staying in memory and ensures logs are safely on disk

compactor:
  working_directory: /loki/compactor # downloads index files here, merges them, then puts them back.
  compaction_interval: 10m # How often
  retention_enabled: true # enable automatic log deletion
  retention_delete_delay: 2h # Wait before actually deleting
  retention_delete_worker_count: 150 # How many parallel workers handle the actual file deletion.
  delete_request_store: filesystem

limits_config:
  retention_period: 744h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  reject_old_samples: true
  reject_old_samples_max_age: 168h
ruler:
  enabled: false
