services:
  app:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://task-manager-db:${DB_PASSWORD}@pgbouncer:5432/tasks?pgbouncer=true
      REDIS_URL: redis://redis:6379
    restart: unless-stopped 
    deploy:
      replicas: 2
    depends_on:
      migrator:
        condition: service_completed_successfully
      pgbouncer:
        condition: service_started
      redis:
        condition: service_started
      seeder:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:5000/api/health"]
      interval: 30s        # default
      timeout: 5s        
      retries: 3           # default
      start_period: 10s    

  db:
    image: postgres:15.14
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: task-manager-db
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task-manager-db -d tasks"]
      interval: 30s        # Default
      timeout: 10s         
      retries: 3           # Default
      start_period: 30s   

  pgbouncer:
    image: edoburu/pgbouncer:v1.25.1-p0 
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: task-manager-db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: tasks
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      MAX_CLIENT_CONN: "1000"
      DEFAULT_POOL_SIZE: "20"
      MIN_POOL_SIZE: "5"

    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped 

  migrator:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://task-manager-db:${DB_PASSWORD}@pgbouncer:5432/tasks?pgbouncer=true
    command: npx prisma migrate deploy
    depends_on:
      pgbouncer:
        condition: service_started
    volumes:
      - ./prisma:/app/prisma:ro
  
  seeder:
    image: ${DOCKER_USERNAME}/${IMAGE_NAME}:latest
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://task-manager-db:${DB_PASSWORD}@pgbouncer:5432/tasks?pgbouncer=true
    command: npm run seed
    depends_on:
      migrator:
        condition: service_completed_successfully

  redis:
    image: redis:alpine3.22
    container_name: redis
    command: redis-server --loglevel warning
    restart: unless-stopped 
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:stable-alpine3.21
    environment:
    - NGINX_ENTRYPOINT_QUIET_LOGS=1
    restart: unless-stopped  
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /home/deployment/task-flow/client:/var/www/task-flow-client:ro
      - /home/deployment/task-flow/admin:/var/www/task-flow-admin:ro
      - /etc/letsencrypt/live/api.desonames.xyz/fullchain.pem:/etc/nginx/certs/api.desonames.xyz/fullchain.pem:ro
      - /etc/letsencrypt/live/api.desonames.xyz/privkey.pem:/etc/nginx/certs/api.desonames.xyz/privkey.pem:ro
      - /etc/letsencrypt/live/task-flows.tech/fullchain.pem:/etc/nginx/certs/task-flows.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/task-flows.tech/privkey.pem:/etc/nginx/certs/task-flows.tech/privkey.pem:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy

  loki:
    image: grafana/loki:3.0.0 
    container_name: loki
    restart: unless-stopped 
    volumes:
      - ./monitor/loki-config.yml:/etc/loki/local-config.yml
      - ./loki/rules:/loki/rules
      - logs_data:/loki
    command: -config.file=/etc/loki/local-config.yml

  prometheus:
    image: prom/prometheus:v2.50.1 
    container_name: prometheus
    restart: unless-stopped  
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitor/rules.yml:/etc/prometheus/rules/rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=72h'
      - '--web.enable-lifecycle'
      - '--log.level=warn' 

  promtail:
    image: grafana/promtail:2.9.5 
    container_name: promtail
    restart: unless-stopped 
    volumes:
      - ./monitor/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_started

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    restart: unless-stopped 
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD}
      - GF_LOG_LEVEL=warn
    depends_on:
      loki:
        condition: service_started
      prometheus:
        condition: service_started 

  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    restart: unless-stopped   
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # to monitor and restart containers

volumes:
  postgres_data:
  logs_data:
  redis_data:
  prometheus_data: